import React from 'react';
import { ScrollView, View, Text, StyleSheet } from 'react-native';

const PrivacyPolicyScreen: React.FC = () => {
    return (
        <ScrollView style={styles.container}>
            <View style={styles.innerContainer}>
                <View style={styles.header}>
                    <Text style={styles.headerTitle}>Privacy Policy for QuitTrack</Text>
                    <Text style={styles.headerSubtitle}>Last Updated: July 29, 2024</Text>
                </View>

                <View style={styles.contentContainer}>
                    <Text style={styles.paragraph}>Welcome to QuitTrack. Your privacy is critically important to us. This Privacy Policy explains how we handle your information within our application.</Text>
                    
                    <View style={styles.section}>
                        <Text style={styles.sectionTitle}>The Core Principle: Your Data is Yours</Text>
                        <Text style={styles.paragraph}>QuitTrack is designed with a "privacy-first" approach. <Text style={styles.bold}>All the personal data you enter into this application is stored exclusively on your local device (in your browser's local storage).</Text> We do not have a central server, we do not create user accounts, and we cannot access, view, share, or sell your data.</Text>
                    </View>

                    <View style={styles.section}>
                        <Text style={styles.sectionTitle}>Information We Collect (Locally)</Text>
                        <View style={styles.list}>
                            <Text style={styles.listItem}>• <Text style={styles.bold}>Onboarding Information:</Text> Data you provide when setting up your plan, such as age, country of residence, nicotine consumption habits, health conditions, and reasons for quitting.</Text>
                            <Text style={styles.listItem}>• <Text style={styles.bold}>Consumption Logs:</Text> The daily entries you make to track your nicotine intake.</Text>
                            <Text style={styles.listItem}>• <Text style={styles.bold}>Personalized Plan:</Text> The quitting plan generated by the AI, which is also stored on your device.</Text>
                        </View>
                    </View>

                    <View style={styles.section}>
                        <Text style={styles.sectionTitle}>How We Use Your Information</Text>
                        <Text style={styles.paragraph}>Your information is used solely within the application to provide you with its features:</Text>
                        <View style={styles.list}>
                            <Text style={styles.listItem}>• To create and display your personalized quitting plan.</Text>
                            <Text style={styles.listItem}>• To track your daily progress against your goals.</Text>
                            <Text style={styles.listItem}>• To calculate achievements like money saved and time gained.</Text>
                            <Text style={styles.listItem}>• To provide context for the AI-powered progress summaries.</Text>
                        </View>
                    </View>
                    
                    <View style={styles.section}>
                        <Text style={styles.sectionTitle}>Third-Party Services: Google Gemini API</Text>
                        <Text style={styles.paragraph}>To provide intelligent features like plan generation and progress summaries, QuitTrack sends some of your anonymized data to the Google Gemini API. </Text>
                        <View style={styles.list}>
                            <Text style={styles.listItem}>• <Text style={styles.bold}>What is Sent:</Text> When you request a plan or an AI summary, the relevant, non-identifiable data points (e.g., your answers from onboarding, recent log history) are sent to the API for processing.</Text>
                            <Text style={styles.listItem}>• <Text style={styles.bold}>Anonymity:</Text> This data is not linked to any personal identifiers. We do not send your name, email, or any unique device ID.</Text>
                            <Text style={styles.listItem}>• <Text style={styles.bold}>Purpose:</Text> The sole purpose of sending this data is to receive the AI-generated response that powers the app's features. The data is not used for any other purpose.</Text>
                        </View>
                    </View>

                    <View style={styles.section}>
                        <Text style={styles.sectionTitle}>Data Deletion</Text>
                        <Text style={styles.paragraph}>You have complete control over your data. You can delete all your information at any time by using the "Start a New Plan" button in the Profile section, which will overwrite all existing data.</Text>
                    </View>
                    
                    <View style={styles.section}>
                        <Text style={styles.sectionTitle}>Changes to This Privacy Policy</Text>
                        <Text style={styles.paragraph}>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.</Text>
                    </View>

                    <View style={styles.section}>
                        <Text style={styles.sectionTitle}>Contact Us</Text>
                        <Text style={styles.paragraph}>If you have any questions about this Privacy Policy, you can contact us at: <Text style={styles.link}>support@quittrack.example.com</Text> (placeholder).</Text>
                    </View>
                </View>
            </View>
        </ScrollView>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    innerContainer: {
        padding: 16,
        maxWidth: 800,
        alignSelf: 'center',
    },
    header: {
        marginBottom: 32,
    },
    headerTitle: {
        fontSize: 30,
        fontWeight: 'bold',
        textAlign: 'center',
        color: '#1e293b',
    },
    headerSubtitle: {
        textAlign: 'center',
        color: '#64748b',
        marginTop: 8,
    },
    contentContainer: {
        // Styles for the main content area
    },
    section: {
        marginBottom: 24,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '600',
        marginBottom: 8,
        color: '#1e293b',
    },
    paragraph: {
        fontSize: 16,
        lineHeight: 24,
        color: '#334155',
    },
    list: {
        marginLeft: 16,
    },
    listItem: {
        fontSize: 16,
        lineHeight: 24,
        color: '#334155',
        marginBottom: 8,
    },
    bold: {
        fontWeight: 'bold',
    },
    link: {
        color: '#0ea5e9',
    },
});

export default PrivacyPolicyScreen;
